---
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:9.9.0

whitelist: &whitelist
  paths:
    - .npmignore
    - lib/*
    - node_modules/*
    - src/*
    - LICENSE.md
    - package.json
    - README.md
    - tsconfig.json
    - tslint.json


version: 2

jobs:

  checkout:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run TSLint
          command: tslint -c tslint.json --project tsconfig.json

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Compile TypeScript
          command: yarn build
      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Write NPM Token to ~/.npmrc
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Install dot-json package
          command: npm install dot-json
      - run:
          name: Write version to package.json
          command: $(yarn bin)/dot-json package.json version ${CIRCLE_TAG:1}
      - run:
          name: Publish to NPM
          command: npm publish --access=public


workflows:
  version: 2

  build:
    jobs:
      - checkout
      - lint:
          requires:
            - checkout
      - build:
          requires:
            - lint

  release:
    jobs:
      - checkout:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - lint:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
          requires:
            - checkout
      - build:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
          requires:
            - lint
      - deploy:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
          requires:
            - build
